### ISSUE TITLE
Switch to standard ES6 promises.

### ISSUE THREAD

**Issue by MicahZoltu** [LedgerHQ/ledger-node-js-api#10]
Putting this in mainly for tracking purposes as I know that this is a pretty significant (semver major) change.  Now that ES2015 officially supports promises and they are available in most browsers, it would be nice if this library used them rather than the legacy non-standard promises available via the `q` library.  Details about A+ promises can be found at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

If you would be open to a Pull Request, let me know.  No promises I'll carve out the time to do it, but if I get annoyed enough with dealing with `q` I may.

**Comment by SilentCicero** [comment]
Agreed, `.fail` !== standard/normal/good.

**Comment by gre** [comment]
this should be fixed on master :)

**Comment by MicahZoltu** [comment]
When should I expect this to make it into an NPM release?  Will it be semver major?  Asking so I can make arrangements to integrate the changes into https://github.com/ethereumjs/ethereumjs-ledger/
