### ISSUE TITLE
Ethereum message signing hex preview incorrect

### ISSUE THREAD

**Issue by fabioberger** [LedgerHQ/ledger-node-js-api#17]
I'm unsure if this issue is related to a firmware issue or how the node library chunks the signing message in `signPersonalMessage_async`: 

https://github.com/LedgerHQ/ledger-node-js-api/blob/23ee17b401fd3dbb122f51ffca5c8119bc52c72e/src/ledger-eth.js#L120

So I thought I'd link to the issue I opened here: https://github.com/LedgerHQ/lib-ledger-core/issues/2 in this repo as well.

**Comment by btchip** [comment]
This other hash is the sha256 hash of the message you're signing - it has been implemented this way so the user can verify it using a third party hashing solution not aware of specific Ethereum rules if the message is long - closing it here
