### ISSUE TITLE
Cannot seem to communicate with device

### ISSUE THREAD

**Issue by mandelmonkey** [LedgerHQ/ledger-node-js-api#3]
I enabled browser mode on my ledger nano s and am running in the browser

`if (typeof ledger == "undefined") {
        ledger = require('ledgerco');
        comm = ledger.comm_node;
        browser = false;
}
else {
        browser = true;
        comm = ledger.comm_u2f;
}

function runTest() {

	ledger.comm_u2f.create_async(0, true).then(function(comm) {

	var btc = new ledger.btc(comm);
	var tx1 = btc.splitTransaction("01000000014ea60aeac5252c14291d428915bd7ccd1bfc4af009f4d4dc57ae597ed0420b71010000008a47304402201f36a12c240dbf9e566bc04321050b1984cd6eaf6caee8f02bb0bfec08e3354b022012ee2aeadcbbfd1e92959f57c15c1c6debb757b798451b104665aa3010569b49014104090b15bde569386734abf2a2b99f9ca6a50656627e77de663ca7325702769986cf26cc9dd7fdea0af432c8e2becc867c932e1b9dd742f2a108997c2252e2bdebffffffff0281b72e00000000001976a91472a5d75c8d2d0565b656a5232703b167d50d5a2b88aca0860100000000001976a9144533f5fb9b4817f713c48f0bfe96b9f50c476c9b88ac00000000");
	btc.createPaymentTransactionNew_async([ [tx1, 1] ], ["0'/0/0"], undefined, "01905f0100000000001976a91472a5d75c8d2d0565b656a5232703b167d50d5a2b88ac").then(function(result) {
		console.log(result);
	}).fail(function(ex) {console.log(ex);});

}).fail(function(ex) {console.log(ex);});

}

if (!browser) {
	runTest();
}
`

however I get an error in the javascript console

<img width="1642" alt="screen shot 2017-02-21 at 2 19 08 pm" src="https://cloud.githubusercontent.com/assets/6570295/23151790/ca6d4dcc-f840-11e6-9e11-5f4e38f7a55b.png">

**Comment by btchip** [comment]
Mmh, that one is weird. 

A few things to check 

- Can you verify that you're running from an HTTPS origin ? 
- Which application are you using ? Can you verify that it is the Bitcoin application ? 
- Can you verify that communication with another application using a similar API (such as BitGo or MyEtherWallet with the ETH application) is working ? 

Thanks

**Comment by mandelmonkey** [comment]
>Can you verify that you're running from an HTTPS origin ?
I was actually running the files locally from my pc, I cloned the repo and opened in my browser

>Which application are you using ? Can you verify that it is the Bitcoin application ?
On my ledger nano s I opened the bitcoin application

>Can you verify that communication with another application using a similar API (such as BitGo or >MyEtherWallet with the ETH application) is working ?

Seems to be same issue with ether tired running testEth 
note I changed 
ledger.comm_node.create_async(0, true).then(function(comm) {
to as I am running in the browser
ledger.comm_u2f.create_async(0, true).then(function(comm) {

`
if (typeof ledger == "undefined") {
        ledger = require('ledgerco');
        comm = ledger.comm_node;
        browser = false;
}
else {
        browser = true;
        comm = ledger.comm_u2f;
}

function runTest() {

ledger.comm_u2f.create_async(0, true).then(function(comm) {

	var eth = new ledger.eth(comm);
	eth.getAppConfiguration_async().then(function(result) {
		console.log(result);
	}).fail(function(ex) {console.log(ex);});

}).fail(function(ex) {console.log(ex);});

}

if (!browser) {
	runTest();
}

`

**Comment by mandelmonkey** [comment]
>Can you verify that you're running from an HTTPS origin ?
I was actually running the files locally from my pc, I cloned the repo and opened in my browser

Which application are you using ? Can you verify that it is the Bitcoin application ?
On my ledger nano s I opened the bitcoin application

Can you verify that communication with another application using a similar API (such as BitGo or MyEtherWallet with the ETH application) is working ?

Seems o be same issue with ether tired running testEth

**Comment by mandelmonkey** [comment]
I will try with https seems it may be the issue
