### ISSUE TITLE
Update node-hid

### ISSUE THREAD

**Issue by bartekn** [LedgerHQ/ledger-node-js-api#35]
It includes a fix for https://github.com/node-hid/node-hid/issues/226

**Comment by zavan** [comment]
Would probably fix the problem I have when installing node-hid on MacOS too:

`
ZavanMacBookPro:ledger-test zavan$ yarn add ledgerco
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠄ node-hid: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
error /Users/zavan/projects/js/ledger-test/node_modules/node-hid: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/zavan/projects/js/ledger-test/node_modules/node-hid
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@9.3.0 | darwin | x64
node-pre-gyp info check checked for "/Users/zavan/projects/js/ledger-test/node_modules/node-hid/build/Release/HID.node" (not found)
node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/zavan/projects/js/ledger-test/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:389:16)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:152:19)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/9.3.0_1/bin/node" "/Users/zavan/projects/js/ledger-test/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zavan/projects/js/ledger-test/node_modules/node-hid
node-pre-gyp ERR! node -v v9.3.0
`

**Comment by gre** [comment]
thanks for raising the issue we have fixed it during the internal es6 refactoring :) it's on master
