### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by LogvinovLeon** [LedgerHQ/ledger-node-js-api#9]
We have a 20s timeout [here](https://github.com/LedgerHQ/ledger-node-js-api/blob/e75e026a7b477d55e051eb7ac26f36d70683f7cf/src/ledger-comm-u2f.js#L95) 
It would be nice to have it as a parameter that defaults to 20s.

**Comment by btchip** [comment]
Done wirth #13 merge
